Fix AttributeError for ImageAssembler in PretrainedPipeline
- When PretrainedPipeline is used in Python with ImageAssembler it will fail with `AttributeError: module 'sparknlp' has no attribute 'ImageAssembler'`